media: cms/media
content:
  - name: posts
    label: Posts
    type: collection
    path: cms/posts
    format: json
    view:
      fields: [title, published, date]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
  - name: pages
    label: pages
    path: cms/pages
    type: collection
    format: json
    fields:
      - name: webProducerKey
        label: The Gilbert template to use to render the home page
        type: string
      - name: title
        label: The title of the home page to show in the browser tab
        type: string
      - name: heading
        label: I can't remember
        type: string
      - name: summary
        label: The summary text for the page
        type: rich-text
  - name: home
    label: Home Page
    path: home.json
    type: file
    fields:
      - name: webProducerKey
        label: The Gilbert template to use to render the home page
        type: string
      - name: title
        lable: The title of the home page to show in the browser tab
        type: string
      - name: heading
        label: I can't remember
        type: string
      - name: summary
        label: The summary text for the page
        type: rich-text
