media:
  input: cms/media
  output: /files/media
content:
  - name: home
    label: Home Page
    path: cms/home.json
    type: file
    fields:
      - name: uri
        label: The unique page slug
        type: string
        pattern: ^\/[a-zA-Z0-9-/]+\.[a-z0-9]*$
      - name: webProducerKey
        label: webProducerKey (template to use)
        options:
          values: [404, home, portfolio, hire-me, uses, simple]
      - name: title
        label: The title of the home page to show in the browser tab
        type: string
      - name: cover
        label: Cover
        type: image
      - name: heading
        label: The page heading-1 if different than the page title
        type: string
      - name: summary
        label: The summary text for the page
        type: rich-text
      - name: body1
        label: Body part one
        type: rich-text
        format: markdown
      - name: body2
        label: Body part two
        type: rich-text
        format: markdown
  - name: simple
    label: Simple pages
    type: collection
    path: cms/simple
    icon: box
    format: json
    fields:
      - name: uri
        label: The unique page slug
        type: string
        pattern: ^\/[a-zA-Z0-9-/]+\.[a-z0-9]*$
      - name: webProducerKey
        label: webProducerKey (template to use)
        options:
          values: [404, home, portfolio, hire-me, uses, simple]
      - name: title
        label: The title of the home page to show in the browser tab
        type: string
      - name: cover
        label: Cover
        type: image
      - name: heading
        label: The page heading-1 if different than the page title
        type: string
      - name: summary
        label: The summary text for the page
        type: rich-text
      - name: body
        label: Body
        type: rich-text
        format: markdown
