media:
  input: src/media
  output: /media
content:
  - name: home
    label: Home
    path: cms/home.json
    type: file
    fields:
      - name: uri
        label: The unique page slug
        type: string
        default: /index.html
        pattern: ^\/[a-zA-Z0-9-/]+\.[a-z0-9]*$
      - name: webProducerKey
        label: webProducerKey (template to use)
        type: select
        options:
          values: ["404", "home", "portfolio", "hire-me", "uses", "simple"]
        default: home
        
      - name: title
        label: The title to show in the browser tab
        type: string
      - name: pageTitle
        label: The title to display on the page
        type: string
      - name: pageSubTitle
        label: The line to display immediately below the title on the page
        type: string
        
      - name: cover
        label: Cover
        type: image
      - name: heading
        label: The page heading-1 if different than the page title
        type: string
      - name: introText
        type: text
        label: Intro Text
      - name: summary
        label: The summary text for the page
        type: rich-text
      - name: body1
        label: Body part one
        type: rich-text
      - name: body2
        label: Body part two
        type: rich-text
        
      - name: meta
        type: object
        fields:
          - name: description
            label: Description
            type: string
          - name: robots
            label: Robots
            type: select
            options:
              values: ["index, follow", "noindex, nofollow", "noindex, follow", "index, nofollow"]
            default: "index, follow"
          - name: ogTitle
            label: og:title
            type: string
          - name: ogDescription
            label: og:description
            type: string
          - name: ogType
            label: og:type
            type: string
          - name: ogImage
            label: og:image
            type: image
          - name: ogUrl
            label: og:url
            type: string
          - name: ogSiteName
            label: og:site_name
            type: string

  - name: about
    label: About
    path: cms/about.json
    type: file
    fields:
      - name: uri
        label: The unique page slug
        type: string
        default: /about.html
        pattern: ^\/[a-zA-Z0-9-/]+\.[a-z0-9]*$
      - name: webProducerKey
        label: webProducerKey (template to use)
        type: select
        options:
          values: ["404", "home", "portfolio", "hire-me", "uses", "simple", "about"]
        default: about
        
      - name: title
        label: The title to show in the browser tab
        type: string
      - name: pageTitle
        label: The title to display on the page
        type: string
      - name: pageSubTitle
        label: The line to display immediately below the title on the page
        type: string
        
      - name: cover
        label: Cover
        type: image
      - name: inspiration
        label: Inspiration
        type: object
        fields:
          - name: heading
            label: Heading
            type: string
          - name: content
            label: Content
            type: rich-text
          - name: image
            label: Image
            type: image

      - name: howIGotHere
        label: How I got here
        type: object
        fields:
          - name: heading
            label: Heading
            type: string
            default: How I Got Here
          - name: body
            label: Body
            type: text

      - name: myValuesAndBeliefs
        label: My Values and Beliefs
        type: string

      - name: whyWorkWithMe
        label: Why Work With Me
        type: object
        fields:
          - name: heading
            label: Heading
            type: string
            default: Why Work With Me
          - name: body
            label: Body
            type: rich-text

      - name: aFewMoreWordsAboutMyself
        label: A Few More Words About Myself
        type: object
        fields:
          - name: heading
            label: Heading
            type: string
            default: A Few More Words About Myself
          - name: body
            label: Body
            type: rich-text
      - name: meta
        type: object
        fields:
          - name: description
            label: Description
            type: string
          - name: robots
            label: Robots
            type: select
            options:
              values: ["index, follow", "noindex, nofollow", "noindex, follow", "index, nofollow"]
            default: "index, follow"
          - name: ogTitle
            label: og:title
            type: string
          - name: ogDescription
            label: og:description
            type: string
          - name: ogType
            label: og:type
            type: string
          - name: ogImage
            label: og:image
            type: image
          - name: ogUrl
            label: og:url
            type: string
          - name: ogSiteName
            label: og:site_name
            type: string
      
  - name: services
    label: Services
    path: cms/services.json
    type: file
    fields:
      - name: uri
        label: The unique page slug
        type: string
        default: /services.html
        pattern: ^\/[a-zA-Z0-9-/]+\.[a-z0-9]*$
      - name: webProducerKey
        label: webProducerKey (template to use)
        type: select
        options:
          values: ["404", "home", "portfolio", "hire-me", "uses", "simple", "about", "services"]
        default: services
      
      - name: title
        label: The title to show in the browser tab
        type: string
      - name: pageTitle
        label: The title to display on the page
        type: string
      - name: pageSubTitle
        label: The line to display immediately below the title on the page
        type: string
  
      - name: meta
        type: object
        fields:
          - name: description
            label: Description
            type: string
          - name: robots
            label: Robots
            type: select
            options:
              values: ["index, follow", "noindex, nofollow", "noindex, follow", "index, nofollow"]
            default: "index, follow"
          - name: ogTitle
            label: og:title
            type: string
          - name: ogDescription
            label: og:description
            type: string
          - name: ogType
            label: og:type
            type: string
          - name: ogImage
            label: og:image
            type: image
          - name: ogUrl
            label: og:url
            type: string
          - name: ogSiteName
            label: og:site_name
            type: string
      - name: cover
        label: Cover
        type: image
  

  - name: projects
    label: Projects
    path: cms/projects.json
    type: file
    fields:
      - name: uri
        label: The unique page slug
        type: string
        default: /projects.html
        pattern: ^\/[a-zA-Z0-9-/]+\.[a-z0-9]*$
      - name: webProducerKey
        label: webProducerKey (template to use)
        type: select
        options:
          values: ["404", "home", "projects", "hire-me", "uses", "simple", "about"]
        default: projects
        
      - name: title
        label: The title to show in the browser tab
        type: string
      - name: pageTitle
        label: The title to display on the page
        type: string
      - name: pageSubTitle
        label: The line to display immediately below the title on the page
        type: string
      - name: cover
        label: Cover
        type: image

      - name: meta
        type: object
        fields:
          - name: description
            label: Description
            type: string
          - name: robots
            label: Robots
            type: select
            options:
              values: ["index, follow", "noindex, nofollow", "noindex, follow", "index, nofollow"]
            default: "index, follow"
          - name: ogTitle
            label: og:title
            type: string
          - name: ogDescription
            label: og:description
            type: string
          - name: ogType
            label: og:type
            type: string
          - name: ogImage
            label: og:image
            type: image
          - name: ogUrl
            label: og:url
            type: string
          - name: ogSiteName
            label: og:site_name
            type: string

  - name: contact
    label: Contact
    path: cms/contact.json
    type: file
    fields:
      - name: uri
        label: The unique page slug
        type: string
        default: /projects.html
        pattern: ^\/[a-zA-Z0-9-/]+\.[a-z0-9]*$
      - name: webProducerKey
        label: webProducerKey (template to use)
        type: select
        options:
          values: ["404", "home", "projects", "contact", "uses", "simple", "about"]
        default: contact
        
      - name: title
        label: The title to show in the browser tab
        type: string
      - name: pageTitle
        label: The title to display on the page
        type: string
      - name: pageSubTitle
        label: The line to display immediately below the title on the page
        type: string
      - name: cover
        label: Cover
        type: image

      - name: meta
        type: object
        fields:
          - name: description
            label: Description
            type: string
          - name: robots
            label: Robots
            type: select
            options:
              values: ["index, follow", "noindex, nofollow", "noindex, follow", "index, nofollow"]
            default: "index, follow"
          - name: ogTitle
            label: og:title
            type: string
          - name: ogDescription
            label: og:description
            type: string
          - name: ogType
            label: og:type
            type: string
          - name: ogImage
            label: og:image
            type: image
          - name: ogUrl
            label: og:url
            type: string
          - name: ogSiteName
            label: og:site_name
            type: string
            
  - name: valuesAndBeliefs
    label: My Values & Beliefs
    type: collection
    path: cms/values
    format: json
    filename: "{year}-{month}-{day}-{primary}.json"
    icon: box
    fields:
      - name: heading
        label: Heading
        type: string
      - name: body
        label: Body
        type: rich-text
        
  - name: simple
    label: Simple pages
    type: collection
    path: cms/simple
    format: json
    filename: "{year}-{month}-{day}-{primary}.json"
    icon: box
    fields:
      - name: uri
        label: The unique page slug
        type: string
        pattern: ^\/[a-zA-Z0-9-/]+\.[a-z0-9]*$
      - name: webProducerKey
        label: webProducerKey (template to use)
        type: select
        options:
          values: ["404", "home", "portfolio", "hire-me", "uses", "simple "]
      - name: meta
        type: object
        fields:
          - name: description
            label: Description
            type: string
          - name: robots
            label: Robots
            type: select
            options:
              values: ["index, follow", "noindex, nofollow", "noindex, follow", "index, nofollow"]
              default: "index, follow"
          - name: ogTitle
            label: og:title
            type: string
          - name: ogDescription
            label: og:description
            type: string
          - name: ogType
            label: og:type
            type: string
          - name: ogImage
            label: og:image
            type: image
          - name: ogUrl
            label: og:url
            type: string
          - name: ogSiteName
            label: og:site_name
            type: string
      - name: title
        label: The title of the home page to show in the browser tab
        type: string
      - name: cover
        label: Cover
        type: image
      - name: heading
        label: The page heading-1 if different than the page title
        type: string
      - name: summary
        label: The summary text for the page
        type: rich-text
      - name: body
        label: Body
        type: rich-text
        format: markdown
