organization: JET
extends:
  - recommended
features.openapi:
  pagination: section
  showConsole: true
  schemaDefinitionsTagName: Schemas
  schemaExpansionLevel: 4
  generateCodeSamples:
    languages:
      - lang: curl
      - lang: Node.js
      - lang: Python
      - lang: C#
apis:
  famstat@v0.1.0:
    root: ./docs/oas/openapi.yaml
